name: learnia
version: 1.0.0+1
description: >-
  Application éducative pour élèves togolais (primaire à terminale) avec IA locale et SQLite.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  provider: ^6.1.1
  image_picker: ^1.0.7
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true 